export const toolbarConfig = {
  undo: { icon: "↶", title: "Undo (Ctrl+Z)" },
  redo: { icon: "↷", title: "Redo (Ctrl+Y)" },
  selectall: { icon: "☍", title: "Select All (Ctrl+A)" },
  h1: { icon: "H1", title: "Heading 1" },
  h2: { icon: "H2", title: "Heading 2" },
  h3: { icon: "H3", title: "Heading 3" },
  h4: { icon: "H4", title: "Heading 4" },
  h5: { icon: "H5", title: "Heading 5" },
  h6: { icon: "H6", title: "Heading 6" },
  bold: { icon: "B", title: "Bold (Ctrl+B)", tag: "strong" },
  italic: { icon: "I", title: "Italic (Ctrl+I)", tag: "em" },
  underline: { icon: "U", title: "Underline (Ctrl+U)" },
  strikethrough: { icon: "S", title: "Strikethrough" },
  mark: { icon: "🖍", title: "Mark" },
  quote: { icon: "❝", title: "Quote" },
  code: { icon: "</>", title: "Code" },
  sup: { icon: "x²", title: "Superscript" },
  sub: { icon: "x₂", title: "Subscript" },
  link: { icon: "🔗", title: "Link (Ctrl+K)" },
  removeformat: { icon: "✕", title: "Remove Format" },
  paintformat: { icon: "🎨", title: "Format Painter" },
  fontsize: { icon: "A", title: "Font Size" },
  fontcolor: { icon: "🎨", title: "Font Color" },
  backcolor: { icon: "🖌", title: "Background Color" },
  left: { icon: "⬅", title: "Align Left" },
  center: { icon: "↹", title: "Align Center" },
  right: { icon: "➡", title: "Align Right" },
  justify: { icon: "⇹", title: "Justify" },
  indent: { icon: "→|", title: "Increase Indent" },
  outdent: { icon: "|←", title: "Decrease Indent" },
  orderedlist: { icon: "1.", title: "Ordered List" },
  unorderedlist: { icon: "•", title: "Unordered List" },
  tasklist: { icon: "☑", title: "Task List" },
  hr: { icon: "—", title: "Horizontal Divider" },
  checkbox: { icon: "☐", title: "Checkbox" },
  markdown: { icon: "MD", title: "Markdown Mode" },
};

export default toolbarConfig;
